# Generated by Django 2.2.5 on 2019-10-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('authors', models.CharField(max_length=120)),
                ('publishedDate', models.CharField(max_length=120)),
                ('industryIdentifiers', models.CharField(max_length=120)),
                ('pageCount', models.CharField(max_length=120)),
                ('imageLinks', models.CharField(max_length=120)),
                ('language', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=120)),
                ('intitle', models.CharField(blank=True, max_length=120)),
                ('inauthor', models.CharField(blank=True, max_length=120)),
                ('inpublisher', models.CharField(blank=True, max_length=120)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('isbn', models.CharField(blank=True, max_length=120)),
                ('lccn', models.CharField(blank=True, max_length=120)),
                ('oclc', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
